"""Markdown report generator."""

from pathlib import Path
from ..models import ScanResult


def generate(result: ScanResult) -> str:
    q = result.quality
    lines = [
        "# CodeSpy Report",
        "",
        f"**Scanned:** `{result.scanned_path}`  ",
        f"**At:** {result.scanned_at}  ",
        f"**Duration:** {result.duration_seconds}s",
        "",
    ]

    # Quality score
    if q:
        grade_emoji = {"A": "🟢", "B": "🟡", "C": "🟠", "D": "🔴", "F": "⛔"}.get(q.grade, "")
        lines += [
            "## Quality Score",
            "",
            f"**{q.score}/100** — Grade **{q.grade}** {grade_emoji}",
            "",
            "| Dimension | Score |",
            "|---|---|",
            f"| Complexity | {q.complexity_score} |",
            f"| Code Smells | {q.smell_score} |",
            f"| Duplication | {q.duplication_score} |",
            "",
        ]

    # Summary
    lines += [
        "## Summary",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Total Files | {result.total_files} |",
        f"| Total Lines | {result.total_lines:,} |",
        f"| Code Lines | {result.total_code_lines:,} |",
        f"| Comment Lines | {result.total_comment_lines:,} |",
        f"| Blank Lines | {result.total_blank_lines:,} |",
        f"| Functions | {result.total_functions:,} |",
        f"| Classes | {result.total_classes:,} |",
        "",
        "### Languages",
        "",
        "| Language | Files | Code Lines |",
        "|---|---|---|",
    ]
    for lang, stats in sorted(result.languages.items(), key=lambda x: -x[1]["code_lines"]):
        lines.append(f"| {lang} | {stats['files']} | {stats['code_lines']:,} |")

    # Duplication
    if result.duplication:
        d = result.duplication
        lines += [
            "",
            "## Duplication",
            "",
            f"- **Duplicate pairs:** {d.duplicate_pairs}",
            f"- **Duplicated lines:** {d.duplicated_lines}",
            f"- **Duplication %:** {d.duplication_percent:.1f}%",
        ]
        if d.pairs:
            lines += [
                "",
                "| File A | Lines | File B | Lines | Similarity |",
                "|---|---|---|---|---|",
            ]
            for p in d.pairs[:20]:
                lines.append(
                    f"| `{p.file_a}` | {p.lines_a[0]}–{p.lines_a[1]} "
                    f"| `{p.file_b}` | {p.lines_b[0]}–{p.lines_b[1]} "
                    f"| {p.similarity:.0%} |"
                )

    # Smells summary
    if result.total_smells > 0:
        lines += [
            "",
            "## Code Smells",
            "",
            f"**Total smells:** {result.total_smells}",
            "",
            "| Type | Count |",
            "|---|---|",
        ]
        for smell_type, count in sorted(result.smells_by_type.items(), key=lambda x: -x[1]):
            lines.append(f"| {smell_type} | {count} |")

    # Complexity hotspots
    all_hotspots = [
        (f.path, h)
        for f in result.files
        if f.complexity
        for h in f.complexity.hotspots
    ]
    all_hotspots.sort(key=lambda x: -x[1].complexity)
    if all_hotspots:
        lines += [
            "",
            "## Complexity Hotspots",
            "",
            "| File | Function | Complexity | Line |",
            "|---|---|---|---|",
        ]
        for path, h in all_hotspots[:20]:
            lines.append(f"| `{path}` | `{h.name}` | {h.complexity} | {h.line} |")

    # Per-file table
    lines += [
        "",
        "## Files",
        "",
        "| File | Language | Lines | Code | Comments | Functions | Classes |",
        "|---|---|---|---|---|---|---|",
    ]
    for f in sorted(result.files, key=lambda x: -x.code_lines):
        lines.append(
            f"| `{f.path}` | {f.language} | {f.lines} "
            f"| {f.code_lines} | {f.comment_lines} "
            f"| {f.functions} | {f.classes} |"
        )

    lines += ["", "---", "*Generated by [codespy](https://github.com/)*"]
    return "\n".join(lines)


def write(result: ScanResult, output_path: str) -> None:
    Path(output_path).write_text(generate(result), encoding="utf-8")
